### ISSUE TITLE
Error: Failed to convert schema undefined: Error: Must provide name.

### ISSUE THREAD

**Issue by shabbyrobe** [lifeomic/json-schema-to-graphql-types#18]
I have the following schema (`schema.json`):

```
{
  "$schema": "http://json-schema.org/schema#",
  "definitions": {
    "Thing": {
      "$id": "#thing",
      "type": "object",
      "required": [
        "Name"
      ],
      "properties": {
        "Name": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}
```

I see the following when I run `convert-json-schemas-to-graphql-types`:

```
$ convert-json-schemas-to-graphql-types  .
Error: Failed to convert schema undefined: Error: Must provide name.
    at convertSchemas (/blah/blah/blah/@lifeomic/json-schema-to-graphql-types/bin/convert-json-schemas-to-graphql-types.js:22:13)
    at convertDir (/blah/blah/blah/@lifeomic/json-schema-to-graphql-types/bin/convert-json-schemas-to-graphql-types.js:54:3)
```

The tool also fails with the same errors with the examples on this page: http://json-schema.org/learn/miscellaneous-examples.html

**Comment by mdlavin** [comment]
It doesn't surprise me that the example that you included fails. When I
look at that schema I see a definition of a type that might be used by
something else but there is no top level type in the schema file.

The examples in the link you sent look more like what I am used to seeing.
I'm surprised that they don't work. I'll take a look at those to see if I
can reproduce your errors

**Comment by MorganHuegel** [comment]
I am also getting the same error with a very simple schema
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/product.schema.json",
  "title": "Product",
  "description": "A product in the catalog",
  "type": "string"
}
```

**Comment by MorganHuegel** [comment]
Hi Matt,
Good point on the string-type.  I did edit my original comment on the issue
so that it was more descriptive.  But yes, let me pull the code and play
around with it today.

**Comment by MorganHuegel** [comment]
I don't have access to create a PR for this repo, so I created one on my own public repo that is a clone of this repo https://github.com/MorganHuegel/convert-json-schemas-to-graphql-types/pull/1 . There are a lot of edge cases, but the update manages some of the obvious ones.

**Comment by mdlavin** [comment]
Thank you for looking into it. I'll try to check out your changes soon and
get back to you.

I think that if you push a branch to your repo, then you can create a PR
here pulling from your repo's branch. If that's not allowed I might have
this project's setting messed up

**Comment by MorganHuegel** [comment]
You are correct; I just had to fork instead of clone.
