### ISSUE TITLE
JSON Schema support?

### ISSUE THREAD

**Issue by avdv** [lifeomic/json-schema-to-graphql-types#47]
Hi.

Which JSON schema version does this tool target / support?

**Comment by mdlavin** [comment]
I'm not sure we've done a full analysis of spec support. I started it a year or two ago, and it's worked well enough for our use. 

If you'd like to do an analysis and contribute some updated docs, that would be great!

**Comment by avdv** [comment]
Hi, thanks for your reply. And sorry for hijacking an issue for my question.

It's just that I tried to convert my schema and got an exception. Seems like `const` is not supported, although `enum` is. And `const` was introduced in draft-06, so parsing is probably limited to draft-04...
